---
upload_path: 'site/static/uploads/:year:/:month:'
frontmatter_file_url_template: 'site/static/uploads/:year:/:month:'
body_file_url_template: 'site/static/uploads/:year:/:month:'
new_page_extension: md
auto_deploy: 
admin_path: 
webhook_url: 
sections:
  post:
    default_front_matter_template: post
  country:
    default_front_matter_template: country
version: '0.26'
