baseurl = "https://happeatravels.com"
languageCode = "en-us"
languageLang = "en"
title = "Happea Travels - a travel blog by Ina and Jayphen"

sectionPagesMenu = "main"

disqusShortname = "happeatravels"
