baseurl = "https://human-resource-manager-governors-74351.netlify.com"
languageCode = "en-us"
languageLang = "en"
title = "My new Victor-Hugo site"

sectionPagesMenu = "main"

disqusShortname = "happeatravels"
