baseurl = "https://happeatravels.com/"
languageCode = "en-us"
languageLang = "en"
title = "Happea Travels - a travel blog by Ina and Jayphen"

disqusShortname = "happeatravels"

[[menu.main]]
  name = "All posts"
  identifier = "post"
  url = "/post/"
