baseurl = "https://human-resource-manager-governors-74351.netlify.com"
languageCode = "en-us"
languageLang = "en"
title = "Happea Travels - a travel blog by Ina and Jayphen"

sectionPagesMenu = "main"

disqusShortname = "happeatravels"
