baseurl = "https://happeatravels.com/"
disqusShortname = "happeatravels"
languageCode = "en-us"
languageLang = "en"
title = "Happea Travels - a travel blog by Ina and Jayphen"
[[menu.main]]
identifier = "post"
name = "All posts"
url = "/post/"
